In [1]:
''' 
В тестировании стратегии получаем анализ DebtToAssetsпо заданым параметрам
    + выводим итог за нужный нам период по набору тикеров
    + может добавить колонки из key_metrics и income_statment
    
    ! Важно добавить рекомендованный год, ниже которого в таблицу не попадает (сейчас 2022)
'''

' \nВ тестировании стратегии получаем анализ DebtToAssetsпо заданым параметрам\n    + выводим итог за нужный нам период по набору тикеров\n    + может добавить колонки из key_metrics и income_statment\n    \n    ! Важно добавить рекомендованный год, ниже которого в таблицу не попадает (сейчас 2022)\n'

In [2]:
import fundamentalanalysis as fa
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
import datetime
import statistics as st

%matplotlib inline

In [3]:
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [4]:
# api_key = '00ef9804fcde0edd93b1b4821ee2f06a' #job.chap@icloud.com
# api_key = 'c81352430e2fe3c941faf0814227562b' #jobs.chaps@gmail.com
api_key = 'a765d11740cccfb61177da0ad8699d1e' #job.chap@gmail.com

tickers

In [5]:
''' Колонки '''
ticker = 'AAPL'
# ticker = 'AAPL'



tickers_list = ['AXP', 'INTC', 'AAPL']
# tickers_list = ['ADBE', 'AAPL', 'F']
# tickers_list = ['WBA', 'IRBT', 'WRK', 'CSCO', 'KR']
# tickers_list = ['WBA', 'IRBT', 'WRK', 'CSCO', 'KR', 'ADBE', 'AAPL', 'F']
# tickers_list = ['UAA', 'HBAN', 'HPE', 'IVZ', 'KEY', 'RF', 'BEN', 'WMB', 'DAL', 'GM', 'WRK', 'WFC', 'EBAY', 'VTR', 'AIG', 'MU', 'MET', 'NTAP', 'SYY', 'BXP', 'MNST', 'XOM', 'PYPL', 'DIS', 'TROW', 'HLT', 'QCOM', 'CVX', 'AAPL', 'HON', 'UPS', 'LOW', 'ACN', 'SNPS', 'LRCX', 'BKNG']

''' IT LIST - 23%'''
# tickers_list = ['ACLS', 'LPL', 'RELY', 'GWRE', 'PAYC', 'NCNO', 'APH', 'AVT', 'COUP', 'AMAT'] 
# tickers_list = ['VNT', 'AMD', 'BR', 'ON', 'NET', 'NTAP', 'BAH', 'HPQ', 'PAY', 'BIGC', 'GLW']
# tickers_list = ['WK', 'GDEV', 'AI', 'APPF', 'BDC', 'VRNS', 'DBX', 'SLAB', 'ANSS', 'ATEX', 'OSIS', 'CGNX', 'XM', 'PRGS', 'SUMO']
# tickers_list = ['MKSI', 'SAIC', 'SITM', 'CDW', 'ZM', 'POWI', 'LPSN', 'GTLB', 'TEL', 'SPNS', 'NEWR', 'ABNB', 'APPN'] 
# tickers_list = ['TRMB', 'SHOP', 'SKLZ', 'ALRM', 'SNOW', 'ZBRA', 'DIOD', 'CSGS', 'INTU', 'RAMP', 'TCX', 'UCTT']
# tickers_list = ['QTWO', 'VRSN', 'CACI', 'MDB', 'NOK', 'IDCC', 'TWOU', 'ESTC', 'SQ', 'OLED', 'AFRM']
# tickers_list = ['ADP', 'FARO', 'EVBG', 'RSKD', 'YEXT', 'KD', 'VMW', 'NABL', 'ARW', 'WDAY', 'LFUS', 'KNBE', 'TTD', 'RPD', 'MA']
# tickers_list =  ['SMAR', 'GLBE', 'DT', 'PLTK', 'MNDY', 'AEIS', 'TSM', 'SLP', 'VRT', 'AKAM', 'IBM', 'MRVL', 'ITRI', 'ACIW'] 
# tickers_list = ['CLSK', 'CGNT', 'BOX', 'NTGR', 'SWI', 'FOUR', 'AMKR', 'BFH', 'SNX', 'MSFT', 'TER', 'QCOM', 'POSH', 'SAP', 'GRMN']
# tickers_list = ['LRCX', 'ALGM', 'INTC', 'ENTG', 'PAYX', 'LDOS', 'SPLK', 'AAPL', 'FIS', 'BL', 'WISH', 'QRVO']
# tickers_list = ['BILL', 'IPGP', 'BMI', 'QLYS', 'TTMI', 'EEFT', 'KEYS', 'MSTR', 'CTSH', 'UI', 'RNG', 'DCT']
# tickers_list = ['STNE', 'CRNC', 'JNPR', 'FTNT', 'TEAM', 'INSG', 'CSCO', 'WIX', 'FSLY', 'CHKP', 'AYX', 'ALTR', 'EPAM', 'AMBA']
# tickers_list =  ['CDAY', 'CRUS', 'CEVA', 'ENV', 'ZD', 'SWCH', 'PUBM', 'PSN', 'MEI', 'META', 'WOLF', 'CFLT', 'NXPI', 'KLIC', 'VLDR', 'TLS', 'MSI']
# tickers_list =  ['SYNA', 'PLUS', 'BSY', 'PYPL', 'ADSK', 'AZPN', 'SPSC', 'FORM', 'DOCU', 'VPG', 'CRWD', 'WDC', 'MVIS','ADBE', 'VSAT', 'GDRX', 'DNB', 'PLTR', 'FIVN', 'NTCT', 'FROG']
# tickers_list = ['ADBE', 'COP', 'AMAT', 'MFGP', 'FISV', 'ASAN', 'ALIT', 'DAVA', 'RIOT', 'NCR', 'SMTC', 'EXLS', 'JKHY', 'ORCL', 'APPS', 'U', 'FICO', 'WEX', 'BKI', 'TXN', 'GDDY', 'CRSR', 'MANH', 'LITE', 'MANH', 'TENB', 'LITE']
# tickers_list = ['CLVT', 'XRX', 'ATEN', 'PEGA', 'ANET', ['GEN', 'SNPS', 'NOW', 'MPWR', 'LSCC', 'SCSC', 'TYL', 'TDC', 'DDOG', 'GLOB', 'ZS', 'SSNC', 'CDNS', 'OKTA', 'NTNX']
# tickers_list = ['COHU', 'NATI', 'DDD', 'LSPD', 'PI', 'PINS', 'HUBS', 'DELL', 'AOSL', 'PTC', 'DXC', 'PAR', 'CRM', 'CVLT', 'SPT', 'CIEN', 'FFIV', 'MXL', 'NSSC', 'VRNT', 'MMS', 'ADI', 'STX']
# tickers_list = ['MCHP', 'ONTO', 'IT', 'CYBR', 'WU', 'ZUO', 'SWKS', 'PAGS', 'LAZR', 'LOGI', 'UPWK', 'EGHT', 'NVDA', 'GPN', 'BLKB', 'TWLO']


''' extra1 - ?%  ---> 5rows'''
# tickers_list = ['ACLS', 'LPL', 'RELY', 'GWRE', 'PAYC', 'NCNO', 'APH', 'AVT', 'COUP', 'AMAT', 'VNT', 'AMD', 'BR', 'ON', 'NET', 'NTAP', 'BAH', 'HPQ', 'PAY', 'BIGC', 'GLW', 'WK', 'GDEV', 'AI', 'APPF', 'BDC', 'VRNS', 'DBX', 'SLAB', 'ANSS', 'ATEX', 'OSIS', 'CGNX', 'XM', 'PRGS', 'SUMO', 'MKSI', 'SAIC', 'SITM', 'CDW', 'ZM', 'POWI', 'LPSN', 'GTLB', 'TEL', 'SPNS', 'NEWR', 'ABNB', 'APPN', 'TRMB', 'SHOP', 'SKLZ', 'ALRM', 'SNOW', 'ZBRA', 'DIOD', 'CSGS', 'INTU', 'RAMP', 'TCX', 'UCTT']
''' extra2 - ?%  ---> 10rows'''
# tickers_list = ['QTWO', 'VRSN', 'CACI', 'MDB', 'NOK', 'IDCC', 'TWOU', 'ESTC', 'SQ', 'OLED', 'AFRM', 'ADP', 'FARO', 'EVBG', 'RSKD', 'YEXT', 'KD', 'VMW', 'NABL', 'ARW', 'WDAY', 'LFUS', 'KNBE', 'TTD', 'RPD', 'MA', 'SMAR', 'GLBE', 'DT', 'PLTK', 'MNDY', 'AEIS', 'TSM', 'SLP', 'VRT', 'AKAM', 'IBM', 'MRVL', 'ITRI', 'ACIW', 'CLSK', 'CGNT', 'BOX', 'NTGR', 'SWI', 'FOUR', 'AMKR', 'BFH', 'SNX', 'MSFT', 'TER', 'QCOM', 'POSH', 'SAP', 'GRMN', 'BILL', 'IPGP', 'BMI', 'QLYS', 'TTMI', 'EEFT', 'KEYS', 'MSTR', 'CTSH', 'UI', 'RNG', 'DCT']
''' extra3 - ?%  ---> 15rows'''
# tickers_list = ['BILL', 'IPGP', 'BMI', 'QLYS', 'TTMI', 'EEFT', 'KEYS', 'MSTR', 'CTSH', 'UI', 'RNG', 'DCT', 'STNE', 'CRNC', 'JNPR', 'FTNT', 'TEAM', 'INSG', 'CSCO', 'WIX', 'FSLY', 'CHKP', 'AYX', 'ALTR', 'EPAM', 'AMBA', 'CDAY', 'CRUS', 'CEVA', 'ENV', 'ZD', 'PUBM', 'PSN', 'MEI', 'META', 'WOLF', 'CFLT', 'NXPI', 'KLIC', 'VLDR', 'TLS', 'MSI', 'SYNA', 'PLUS', 'BSY', 'PYPL', 'ADSK', 'AZPN', 'SPSC', 'FORM', 'DOCU', 'VPG', 'CRWD', 'WDC', 'MVIS','ADBE', 'VSAT', 'GDRX', 'DNB', 'PLTR', 'FIVN', 'NTCT', 'FROG', 'ADBE', 'COP', 'AMAT', 'MFGP', 'FISV', 'ASAN', 'ALIT', 'DAVA', 'RIOT', 'NCR', 'SMTC', 'EXLS', 'JKHY', 'ORCL', 'APPS', 'U', 'FICO', 'WEX', 'BKI', 'TXN', 'GDDY', 'CRSR', 'MANH', 'LITE', 'MANH', 'TENB']
''' extra3 - 21%  ---> 18rows'''
# tickers_list = ['CLVT', 'XRX', 'ATEN', 'PEGA', 'ANET', 'GEN', 'SNPS', 'NOW', 'MPWR', 'LSCC', 'SCSC', 'TYL', 'TDC', 'DDOG', 'GLOB', 'ZS', 'SSNC', 'CDNS', 'OKTA', 'NTNX', 'COHU', 'NATI', 'DDD', 'LSPD', 'PI', 'PINS', 'HUBS', 'DELL', 'AOSL', 'PTC', 'DXC', 'PAR', 'CRM', 'CVLT', 'SPT', 'CIEN', 'FFIV', 'MXL', 'NSSC', 'VRNT', 'MMS', 'ADI', 'STX', 'MCHP', 'ONTO', 'IT', 'CYBR', 'WU', 'ZUO', 'SWKS', 'PAGS', 'LAZR', 'LOGI', 'UPWK', 'EGHT', 'NVDA', 'GPN', 'BLKB', 'TWLO']

''' extra98 - ?% '''
# tickers_list = ['WK', 'GDEV', 'AI', 'APPF', 'BDC', 'VRNS', 'DBX', 'SLAB', 'ANSS', 'ATEX', 'OSIS', 'CGNX', 'XM', 'PRGS', 'SUMO', 'ADP', 'FARO', 'EVBG', 'RSKD', 'YEXT', 'KD', 'VMW', 'NABL', 'ARW', 'WDAY', 'LFUS', 'KNBE', 'TTD', 'RPD', 'MA', 'CLVT', 'XRX', 'ATEN', 'PEGA', 'ANET', 'GEN', 'SNPS', 'NOW', 'MPWR', 'LSCC', 'SCSC', 'TYL', 'TDC', 'DDOG', 'GLOB', 'ZS', 'SSNC', 'CDNS', 'OKTA', 'NTNX']
''' extra99 - ?% '''
# tickers_list = ['MKSI', 'SAIC', 'SITM', 'CDW', 'ZM', 'POWI', 'LPSN', 'GTLB', 'TEL', 'SPNS', 'NEWR', 'ABNB', 'APPN', 'SMAR', 'GLBE', 'DT', 'PLTK', 'MNDY', 'AEIS', 'TSM', 'SLP', 'VRT', 'AKAM', 'IBM', 'MRVL', 'ITRI', 'ACIW', 'ACLS', 'LPL', 'RELY', 'GWRE', 'PAYC', 'NCNO', 'APH', 'AVT', 'COUP', 'AMAT', 'QTWO', 'VRSN', 'CACI', 'MDB', 'NOK', 'IDCC', 'TWOU', 'ESTC', 'SQ', 'OLED', 'AFRM']






''' utilities_list - 15% '''
# tickers_list = ['ALE', 'FTCI', 'ARRY', 'PPL', 'STEM', 'CNP', 'SJW', 'UGI', 'EIX', 'CWT', 'NI', 'DUK', 'AWR', 'AWK', 'SRE', 'HE', 'NRG', 'HYLN', 'CMS', 'XEL', 'AES', 'NJR', 'EXC', 'PEG', 'UTL', 'NFG', 'NWE', 'ED', 'D', 'ATO', 'AVA']
# 'SO', 'AEE', 'WEC', 'NEE', 'KEP', 'MDU', 'MSEX', 'ES', 'CWEN', 'PCG', 'ETR', 'FE', 'WTRG', 'AEP', 'EVRG', 'POR', 'IDA', 'PNW', 'LNT']  # 15%

''' CONSUMER LIST - 31%'''
# tickers_list = ['THS', 'DPZ', 'WGO', 'ETD', 'PZZA', 'DG', 'RH', 'BWA', 'CENTA', 'BJ', 'IRBT', 'AOUT', 'HEAR', 'YUMC', 'TPR', 'MBUU', 'CROX', 'SIG', 'CWH', 'DLTR', 'GTX', 'CHGG', 'LOW', 'AZO', 'MELI', 'UAA', 'HOG']
# 'MED', 'PSMT', 'YUM', 'ASO', 'ORLY', 'PRTS', 'PLCE', 'JBSS', 'WH', 'FLWS', 'LEGH', 'ANF', 'MDC', 'RCII', 'YETI', 'HHR', 'GPS', 'WMG', 'VSTO', 'TPH', 'AAP', 'MKC', 'MHK', 'OSTK', 'CRMT', 'TOL', 'NVR', 'DASH', 'EAT', 'HZO', 'CPB', 'CHD', 'BBWI', 'ZUMZ', 'MODG', 'POOL', 'QUOT', 'FL', 'ANDE', 'UDMY', 'SONO', 'MLCO', 'COKE', 'CVCO', 'SAH', 'BROS', 'BKNG', 'ETSY', 'NKE', 'FTDR', 'KHC', 'JOUT', 'UNFI', 'STRA', 'CASY', 'STAA', 'CRI', 'CVGW', 'VC', 'MOV', 'HIBB', 'SAM', 'TNL', 'SPB@US', 'JWN', 'RL', 'SMPL', 'KMX', 'TAP', 'SLVM', 'VIPS', 'GO', 'URBN', 'HBI', 'CENT', 'PHM', 'CNXN', 'BG', 'BLMN', 'REYN', 'GM', 'MCRI', 'WKHS', 'AEO', 'KO', 'ANAB', 'SCI', 'PCTY', 'LEN', 'WBA', 'SHLS', 'MGM', 'SHAK', 'PTON', 'MGPI', 'FLO', 'GNTX', 'LVS', 'BYND', 'KR', 'LANC', 'PPC', 'DUOL', 'BJRI', 'TGT', 'SONY', 'BBY', 'CCL', 'SSTK', 'TJX', 'KSS', 'THO', 'LOPE', 'FNKO', 'FVRR', 'USFD', 'MO', 'DAN', 'JD', 'HAS', 'DKNG', 'OFIX', 'LEVI', 'ACI', 'TXRH', 'H', 'BLNK', 'BURL', 'JJSF', 'SFIX', 'WING', 'NUS', 'CELH', 'OLLI', 'PLAY', 'VAC', 'HRL', 'SJM', 'SKX', 'PII', 'MTH', 'DORM', 'CHH', 'MNST', 'CLX', 'CPS', 'VZIO', 'CAG', 'WW', 'MLKN', 'MAR', 'TTCF', 'HLT', 'TSCO', 'LCII', 'HAIN', 'F', 'WMT', 'TSN', 'QRTEA', 'BUD', 'BZUN', 'DRQ', 'FBIN', 'APPH', 'DRI', 'IBP', 'BGS', 'WCC', 'PFGC', 'PETQ', 'WYNN', 'FTCH', 'BC', 'KTB', 'PAG', 'TM', 'ROST', 'COTY', 'W', 'FRPT', 'TMHC', 'SBH', 'SHOO', 'BRBR', 'PEP', 'DLTH', 'MHO', 'ULTA', 'LEA', 'ZWS', 'USNA', 'MTN', 'RCL', 'TAL', 'RACE', 'DECK', 'COUR', 'WDFC', 'PNTG', 'ADM', 'UA', 'MAT', 'EL', 'GHC', 'WHR', 'ABG', 'RRR', 'AN', 'PCRX', 'LKQ', 'HD', 'IPAR', 'GES', 'SBUX', 'TWNK', 'CPRI', 'CBRL', 'ZIP', 'PG', 'KOPN', 'FND', 'M', 'SYY', 'LRN', 'ATGE', 'NTCO', 'POST', 'DKS', 'FSR', 'METC', 'SFM', 'SNBR', 'HSY', 'BH', 'KDP', 'GIS', 'VFC', 'BTI', 'DHI', 'HRB', 'KBH', 'STZ', 'GT', 'CVNA', 'FIGS', 'KMB', 'PLNT', 'VSCO', 'MGA', 'CPNG', 'CALM', 'DAR', 'HGV', 'CHDN', 'LW', 'COST', 'VERU', 'CZR', 'JBL', 'OTIS', 'THRM', 'FIZZ', 'GPI', 'MCD', 'HLF', 'CL', 'XPEL', 'LEG', 'LI', 'MDLZ', 'JAMF', 'TTM', 'CMG', 'HCC', 'JACK', 'WWW', 'INGR', 'PM', 'BLD', 'EYE', 'MNRO', 'GPRO', 'EBAY', 'BF.B', 'LGIH', 'GCO', 'WSM', 'DM', 'K', 'GPC', 'EXPE', 'ENR', 'BFAM', 'APEI', 'XNCR', 'BIG', 'PVH', 'CHWY', 'NWL', 'BOOT', 'GMS', 'BBBY', 'LULU', 'COLM', 'ARMK', 'WRBY', 'TPX', 'AAN', 'LAD', 'CHEF', 'HTHT', 'AMZN', 'FOXF', 'BABA', 'STLA', 'AZEK', 'RVLV', 'LPX', 'RRGB', 'TSLA', 'RGR', 'VUZI']

''' FINANCIAL LIST - 17%'''
# tickers_list = ['SLM', 'AJG', 'C', 'WTW', 'BOH', 'FAF', 'STWD', 'NTRS', 'ARI', 'ZION', 'CLBK', 'GS', 'MCO', 'CNXC', 'FFIN', 'ECPG', 'HIG', 'RKT', 'VIRT', 'BXMT', 'ORI', 'KEY', 'BLK', 'NIC']
# , 'CB', 'COLB', 'FLT', 'WRLD', 'AON', 'SIGI', 'BMO', 'COIN', 'CBU', 'MKTX', 'HBAN', 'PSEC', 'CNNE', 'RE', 'AIG', 'TRV', 'DLO', 'THG', 'CG', 'NWLI', 'NU', 'CNO', 'BHF', 'KMPR', 'COOP', 'AGO', 'ALLY', 'AMG', 'WABC', 'PMT', 'SYF', 'AFL', 'CINF', 'MARA', 'UNM', 'INDB', 'UMBF', 'BRK.B', 'PFSI', 'PFG', 'PNFP', 'PIPR', 'MET', 'ICE', 'FNF', 'EVR', 'APO', 'FHI', 'AFG', 'UPST', 'BEN', 'LYLT', 'EHTH', 'RF', 'VRTS', 'GBCI', 'COFS', 'USB', 'JHG', 'SI', 'ABCB', 'BOKF', 'NYCB', 'IBTX', 'HASI', 'CBSH', 'ARCC', 'CMA', 'FRC', 'SRC', 'CACC', 'TW', 'CHCO', 'PNC', 'SLQT', 'FRME', 'MMC', 'WTFC', 'XP', 'IVZ', 'COF', 'AMP', 'PRG', 'ABR', 'SCHW', 'RDN', 'SPGI', 'ACGL', 'PGR', 'AXP', 'GSHD', 'WFC', 'SIVB', 'NDAQ', 'MS', 'FCFS', 'FOCS', 'TRUP', 'HLNE', 'NMIH', 'EVER', 'LC', 'TFC', 'MTB', 'EQH', 'FCNCA', 'DFS', 'WBS', 'RY', 'BKU', 'MKL', 'ERIE', 'STT', 'TCBI', 'OMF', 'LPLA', 'RRBI', 'AIZ', 'IBN', 'ESGR', 'GL', 'WRB', 'CNS', 'MQ', 'APAM', 'JPM', 'MTG', 'RJF', 'CME', 'SBNY', 'HLI', 'UBS', 'TROW', 'SOFI', 'MC', 'SF', 'L', 'VOYA', 'HOOD', 'TCS', 'JEF', 'BX', 'BRO', 'IBKR', 'EWBC', 'GATX', 'MORN', 'KNSL', 'AX', 'CFG', 'PRI', 'PRU', 'FITB', 'LPRO', 'AMSF', 'BK', 'BAC', 'TREE', 'V', 'FDS', 'NAVI', 'CFR', 'RNR', 'MSCI', 'RGA', 'LNC', 'CM', 'PB', 'KKR', 'SEIC', 'WAL', 'UBSI', 'ALL', 'FRHC', 'PJT', 'PRAA', 'COWN', 'TPG', 'WAFD', 'SBCF', 'GDOT', 'SSB']



# electrocars_list
#tickers_list =  ['RRX', 'ARVL', 'LCID', 'ALV', 'CHPT']  # 1% sum

#green_energy_list
# tickers_list = ['ORA', 'FSLR', 'RUN', 'NOVA', 'GTLS', 'SEDG'] # 38

# tickers_list = ['F', 'WU', 'KMI', 'CNP', 'HPQ', 'GLW', 'KHC', 'LUV', 'CMCSA', 'NRG', 'BK', 'CSCO', 'USB', 'TJX', 'CAH', 'HIG', 'SCHW', 'HAS', 'WELL']
# tickers_list = ['F', 'WU', 'KMI', 'CNP', 'HPQ', 'GLW', 'KHC', 'LUV', 'CMCSA', 'NRG', 'BK', 'CSCO', 'USB', 'TJX', 'CAH', 'HIG', 'SCHW', 'HAS', 'WELL', 'DXCM', 'ROST', 'GRMN', 'NKE', 'YUM', 'GOOGL', 'JPM', 'GOOG', 'GPN', 'MMM', 'AXP', 'TGT', 'TXN', 'CRM', 'NDAQ', 'CAT', 'ILMN', 'V', 'GD', 'NFLX', 'MSFT', 'HD', 'MA', 'SPGI', 'IDXX', 'ADBE', 'AVGO',
# 'UAA', 'HBAN', 'HPE', 'IVZ', 'KEY', 'RF', 'BEN', 'WMB', 'DAL', 'GM', 'WRK', 'WFC', 'EBAY', 'VTR', 'AIG', 'MU', 'MET', 'NTAP', 'SYY', 'BXP', 'MNST', 'XOM', 'PYPL', 'DIS', 'TROW', 'HLT', 'QCOM', 'CVX', 'AAPL', 'HON', 'UPS']
# tickers_list = ['LRCX', 'BKNG','KEY', 'BAC', 'LVS', 'UAL', 'HOG', 'CFG', 'ALK', 'MAS', 'BBY', 'EMR', 'PSX', 'MS', 'LYB', 'RTX', 'RL', 'COP', 'AMAT', 'QRVO', 'SPG', 'DRI', 'BA', 'META', 'NVDA', 'FDX', 'ADSK', 'ABMD', 'GS',
# 'GPS', 'XRX', 'BKR', 'PARA', 'FCX', 'ALK', 'WDC', 'C', 'MOS', 'OKE', 'DHI', 'BBY', 'MPC', 'AMD', 'PRU', 'EXPE', 'EOG', 'VLO', 'MAR', 'HCA', 'ALB']

' FINANCIAL LIST - 17%'

data

In [6]:
required_year = '2022'


''' время '''
stime='2010-01-01'
ftime='2023-02-01'
period = '1mo'  # '1d' '1wk'

In [7]:
''' добавляем цифру к году, чтобы видень данные как начало года, а не как факт '''
def change_index_plus_one(df):
    df_index = df.index.to_list()
    for i in range(len(df_index)):
        df_index[i] = str(int(df_index[i])+1)
    df['Date_index'] = df_index
    df = df.set_index('Date_index')
    return df

analyse DebtToAssets str

In [8]:
def one_stock_analyse(ticker, api_key, required_year):

    ''' запрос к yahoo'''
    def get_data_from_ticker(tick, interval='1mo'):
        ticker = yf.Ticker(tick)

        df = ticker.history(start='1990-01-01', end=None, interval=interval)
        x = pd.DataFrame(df)
        x.rename(columns={"Close": tick}, inplace=True)
        z = x.drop(columns=["Open", "High", "Low", "Volume", "Dividends", "Stock Splits"])
        return z

    
    df = get_data_from_ticker(ticker)


    ''' функция по изменению индекса в df из yahoo'''
    def change_index(df):
        df_index = df.index.to_list()
        for i in range(len(df_index)):
            t = df_index[i].date()
            df_index[i] = t.strftime('%Y-%m-%d')
        df['Date_index'] = df_index
        df = df.set_index('Date_index')
        return df

    df = change_index(df)

    ''' получаем нужный период key_metrics'''
    def get_key_metricks(ticker, api_key, required_year):
        key_metrics = fa.key_metrics(ticker, api_key, period='annual')
        df_key_metr = key_metrics.T
        df_key_metr = change_index_plus_one(df_key_metr)
        df_key_metr = df_key_metr.loc[required_year:'2000'].copy(deep=True)
        return df_key_metr



    df_key_metr = get_key_metricks(ticker, api_key, required_year)

    ''' проверяем минимальный требуемый уровень и наличие следующего года '''
    if df_key_metr.index[0] >= required_year and f'{int(required_year)+1}-01-01' in df.index.to_list():
        last_year = True
    else:
        last_year = False


    ''' получаем индекс из таблицы чтобы получить цены по ним'''
    def get_index(df):
        index_years = df.index.to_list()
        return index_years

    index_years = get_index(df_key_metr)


    ''' извлекаем цены '''
    def get_price_from_df(df, list_dates):
        new_list = []
        for i in range(len(list_dates)):
            x = int(list_dates[i])
            # x += 1
            x = str(x)
            try:
                r = df.loc[f'{x}-01-01']
                r = float(r)
                new_list.append(r)
            except:
                new_list.append(0)

        return new_list

    
    stock_year_prices = get_price_from_df(df, index_years)

    ''' добавляем цены к метрикам'''
    df_key_metr[ticker] = list(stock_year_prices)
    df_key_metr.drop('period', axis=1, inplace=True)

    
    ''' добавляем колонки с изменением в процентах к предыдущему году '''
    def change_percent_all_columns(df):
        x = df.columns.to_list()
        for i in range(len(x)):
            v = df[x[i]].to_list()
            l = []
            for y in range(len(v)):
                try:
                    if y != len(v):
                        vv = (v[y] / (v[y+1] / 100)) - 100
                        l.append(vv)
                    else:
                        vv = 0
                        l.append(vv)
                except:
                    l.append(0)
            df[f'change % {x[i]}'] = l
        return df

    df_with_changes = change_percent_all_columns(df_key_metr)
    df_with_changes = df_with_changes.reindex(index=df_with_changes.index[::-1])


    df_some_columns = df_with_changes[[f'change % {ticker}', 'change % debtToAssets']]


    # mean_result = st.mean(df_some_columns[f'change % {ticker}'].to_list()[1:])   
    
    
    ''' меняем индекс'''
    df_with_changes.index.name='Date'
    df_with_changes = df_with_changes.reset_index()


    ''' стратегия и сигналы '''
    l = []
    for i in range(len(df_some_columns['change % debtToAssets'])):
        if i <= 1:
            pass
        elif i == len(df_some_columns['change % debtToAssets']) - 1:
            pass
        elif df_with_changes[f'change % {ticker}'][i] < df_with_changes[f'change % {ticker}'][i-1] and df_with_changes['change % debtToAssets'][i] > df_with_changes['change % debtToAssets'][i-1] and df_with_changes['change % debtToAssets'][i] > df_with_changes[f'change % {ticker}'][i]:
            l.append([ticker, df_with_changes['Date'][i], df_with_changes[f'change % {ticker}'][i+1]])
        # elif df_with_changes[f'change % {ticker}'][i] < df_with_changes['change % debtToAssets'][i] and df_with_changes[f'change % {ticker}'][i-1] < df_with_changes['change % debtToAssets'][i-1]:
        #     l.append([ticker, df_with_changes['Date'][i], df_with_changes[f'change % {ticker}'][i+1]])
        # elif df_with_changes[f'change % {ticker}'][i] < df_with_changes['change % debtToAssets'][i]:
        #     l.append([ticker, df_with_changes['Date'][i], df_with_changes[f'change % {ticker}'][i+1]])
        else:
            pass  
    
    df_means_results = pd.DataFrame(l, columns = ['Ticker', 'Date', 'ResultNextYear'])
    print(ticker)

    return df_means_results

In [9]:
# one_stock_analyse(ticker, api_key, required_year)

list analyse

In [10]:
def list_stock_analyse(tickers_list, api_key, required_year):
    l = []
    for i in range(len(tickers_list)):
        try:
            if i == 0:
                df = one_stock_analyse(tickers_list[i], api_key, required_year)
            else:
                df = pd.concat([df, one_stock_analyse(tickers_list[i], api_key, required_year)], ignore_index=True)
        except:
            pass
    return df


df_means_results = list_stock_analyse(tickers_list, api_key, required_year)

AXP
INTC
AAPL

In [11]:
df_means_results

  Ticker  Date  ResultNextYear
0    AXP  2002        0.214107
1    AXP  2015      -32.776406
2    AXP  2016       45.539418
3   INTC  2003       95.618135
4   INTC  2005       -4.037718
5   INTC  2021       -9.771407
6   AAPL  2003       57.102742
7   AAPL  2007       57.890979
8   AAPL  2009      113.092160
9   AAPL  2019       88.752944

add report date

In [12]:
def add_report_date(df):
    v = 'acceptedDate'
    l = []
    for i in range(len(df['Ticker'])):
        if i == 0:
            key_metrics = fa.income_statement(df['Ticker'][i], api_key, period='annual').T
            key_metrics = change_index_plus_one(key_metrics)
            date = df['Date'][i]
            l.append(key_metrics.loc[date, v][:10])

        elif df['Ticker'][i] == df['Ticker'][i-1]:
            date = df['Date'][i]
            l.append(key_metrics.loc[date, v][:10])

        else:
            key_metrics = fa.income_statement(df['Ticker'][i], api_key, period='annual').T
            key_metrics = change_index_plus_one(key_metrics)
            date = df['Date'][i]
            l.append(key_metrics.loc[date, v][:10])
    df[v] = l
    
    return df

df_with_parameters = add_report_date(df_means_results)

In [13]:
df_with_parameters

  Ticker  Date  ResultNextYear acceptedDate
0    AXP  2002        0.214107   2002-04-01
1    AXP  2015      -32.776406   2015-02-23
2    AXP  2016       45.539418   2016-02-19
3   INTC  2003       95.618135   2003-03-10
4   INTC  2005       -4.037718   2005-02-18
5   INTC  2021       -9.771407   2021-01-21
6   AAPL  2003       57.102742   2002-12-19
7   AAPL  2007       57.890979   2006-12-29
8   AAPL  2009      113.092160   2008-11-05
9   AAPL  2019       88.752944   2018-11-05

add prices of start year and finish

In [14]:
def get_start_prices(df):
    
    
    ''' запрос к yahoo '''
    def get_data_from_ticker_wuth_up_end(tick, s_date, interval='1mo'):

        f_date = str(int(s_date[:4]) + 1)

        ticker = yf.Ticker(tick)

        df = ticker.history(start=s_date, end=f'{f_date}{s_date[4:]}', interval=interval)
        x = pd.DataFrame(df)
        x.rename(columns={"Close": tick}, inplace=True)
        z = x.drop(columns=["Open", "High", "Low", "Volume", "Dividends", "Stock Splits"])
        return z
    
    l = []

    for i in range(len(df['Ticker'])):
        prices = get_data_from_ticker_wuth_up_end(df['Ticker'][i], df['acceptedDate'][i])
        
        start_p = prices[df['Ticker'][i]][0]
        l.append(start_p)

    df['start_Price'] = l

    
    return df


df_with_start_price = get_start_prices(df_with_parameters)

add next report date

In [15]:
def add_next_report_date(df):
    l = []
    for i in range(len(df['Ticker'])):
        next_year = int(df['acceptedDate'][i][:4])+1
        next_year = str(next_year) + df['acceptedDate'][i][4:]
        l.append(next_year)
    df['NextReportYear'] = l
    return df
        
    
df_with_next_report = add_next_report_date(df_with_start_price)
df_with_next_report

  Ticker  Date  ResultNextYear acceptedDate  start_Price NextReportYear
0    AXP  2002        0.214107   2002-04-01    26.601015     2003-04-01
1    AXP  2015      -32.776406   2015-02-23    69.237350     2016-02-23
2    AXP  2016       45.539418   2016-02-19    55.252884     2017-02-19
3   INTC  2003       95.618135   2003-03-10    10.802757     2004-03-10
4   INTC  2005       -4.037718   2005-02-18    13.806106     2006-02-18
5   INTC  2021       -9.771407   2021-01-21    56.296223     2022-01-21
6   AAPL  2003       57.102742   2002-12-19     0.218251     2003-12-19
7   AAPL  2007       57.890979   2006-12-29     2.605943     2007-12-29
8   AAPL  2009      113.092160   2008-11-05     2.594391     2009-11-05
9   AAPL  2019       88.752944   2018-11-05    38.003685     2019-11-05

In [16]:
# df_with_parameters.sort_values(by=['ResultNextYear'], ascending=False)

math (get market mean)

In [17]:
''' get market result to compare '''
def get_data_from_ticker(tick, stime, ftime, interval=period):
    ticker = yf.Ticker(tick)

    df = ticker.history(start=stime, end=ftime, interval=interval)
    x = pd.DataFrame(df)
    x.rename(columns={"Close": tick}, inplace=True)
    z = x.drop(columns=["Open", "High", "Low", "Volume", "Dividends", "Stock Splits"])
    return z

df_market = get_data_from_ticker('^GSPC', stime, None, period)
df_market = df_market.reindex(index=df_market.index[::-1])

def change_index(df):
    df_index = df.index.to_list()
    for i in range(len(df_index)):
        t = df_index[i].date()
        df_index[i] = t.strftime('%Y-%m-%d')
    df['Date_index'] = df_index
    df = df.set_index('Date_index')
    return df

df_market = change_index(df_market)

def get_price_from_df(df, stime, ftime):
    new_list = []
    for i in range(int(stime[:4]),int(ftime[:4])):
        x = i
        x += 1
        x = str(x)
        r = df.loc[f'{x}-01-01']
        r = float(r)
        new_list.append(r)
        
    return new_list

df_market_year_velues = get_price_from_df(df_market, stime, ftime)

df_market_year_percents = []
for i in range(len(df_market_year_velues)):
    if i == 0:
        pass
    # elif i == len(df_market_year_velues):
    #     pass
    else:
        df_market_year_percents.append((df_market_year_velues[i] / (df_market_year_velues[i-1]/100))-100)

# st.mean(df_market_year_percents)

math result

In [18]:
st.mean(df_market_year_percents)

10.64730018538931

In [19]:
df_means_results['ResultNextYear'].mean()

41.16249532766831