In [25]:
import fundamentalanalysis as fa
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
import datetime
import statistics as st
from matplotlib.pyplot import figure

%matplotlib inline

In [26]:
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [27]:
# api_key = '00ef9804fcde0edd93b1b4821ee2f06a'
api_key = 'c81352430e2fe3c941faf0814227562b'

data

In [28]:

''' Колонки '''
ticker = 'ATEX'
# ticker = 'AAPL'



''' для фильтрации'''
filt_start_date = '1999'
filt_finish_date = '2022'


''' время '''
stime=f'{str(int(filt_start_date)-1)}-01-01'
ftime='2023-02-01'
period = '1mo'  # '1d' '1wk'

ticker and stock data

In [29]:
def get_data_from_ticker(tick, stime, ftime, interval=period):
    ticker = yf.Ticker(tick)

    df = ticker.history(start=stime, end=ftime, interval=interval)
    x = pd.DataFrame(df)
    x.rename(columns={"Close": tick}, inplace=True)
    z = x.drop(columns=["Open", "High", "Low", "Volume", "Dividends", "Stock Splits"])
    return z

df = get_data_from_ticker(ticker, stime, None, period)
df_market = get_data_from_ticker('^GSPC', stime, None, period)
df.tail(3)

                                ATEX
Date
2022-12-01 00:00:00-05:00  32.169998
2023-01-01 00:00:00-05:00  36.070000
2023-02-01 00:00:00-05:00  34.290001

change index to add in metriks df

In [30]:
def change_index(df):
    df_index = df.index.to_list()
    for i in range(len(df_index)):
        t = df_index[i].date()
        df_index[i] = t.strftime('%Y-%m-%d')
    df['Date_index'] = df_index
    df = df.set_index('Date_index')
    return df

df = change_index(df)
df_market  = change_index(df_market)
df.tail(3)

                 ATEX
Date_index
2022-12-01  32.169998
2023-01-01  36.070000
2023-02-01  34.290001

In [31]:
''' добавляем цифру к году, чтобы видень данные как начало года, а не как факт '''
def change_index_plus_one(df):
    df_index = df.index.to_list()
    for i in range(len(df_index)):
        df_index[i] = str(int(df_index[i])+1)
    df['Date_index'] = df_index
    df = df.set_index('Date_index')
    return df

key_metrics

In [32]:
key_metrics = fa.key_metrics(ticker, api_key, period='annual')
df_key_metr = key_metrics.T
df_key_metr = change_index_plus_one(df_key_metr)
df_key_metr.head(3)

,period,revenuePerShare,netIncomePerShare,operatingCashFlowPerShare,freeCashFlowPerShare,cashPerShare,bookValuePerShare,tangibleBookValuePerShare,shareholdersEquityPerShare,interestDebtPerShare,marketCap,enterpriseValue,peRatio,priceToSalesRatio,pocfratio,pfcfRatio,pbRatio,ptbRatio,evToSales,enterpriseValueOverEBITDA,evToOperatingCashFlow,evToFreeCashFlow,earningsYield,freeCashFlowYield,debtToEquity,debtToAssets,netDebtToEBITDA,currentRatio,interestCoverage,incomeQuality,dividendYield,payoutRatio,salesGeneralAndAdministrativeToRevenue,researchAndDdevelopementToRevenue,intangiblesToTotalAssets,capexToOperatingCashFlow,capexToRevenue,capexToDepreciation,stockBasedCompensationToRevenue,grahamNumber,roic,returnOnTangibleAssets,grahamNetNet,workingCapital,tangibleAssetValue,netCurrentAssetValue,investedCapital,averageReceivables,averagePayables,averageInventory,daysSalesOutstanding,daysPayablesOutstanding,daysOfInventoryOnHand,receivablesTurnover,payablesTurnover,inventoryTurnover,roe,capexPerShare
Date_index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023,FY,0.059748,-2.06798,0.987332,-0.523513,5.821805,10.26841,1.936247,10.26841,0.316654,940524203.52,840589203.52,-25.067944,867.642254,52.505119,-99.023395,5.048493,5.048493,775.451295,-23.996266,46.92621,-88.501706,-0.039892,-0.010099,0.022421,0.329969,2.85284,12.014425,-658,-0.477438,None,0,36.462177,3.314576,0.543687,-1.530229,-25.2869,-18.904138,12.569188,21.858281,-0.137284,-0.295716,0.76493,106135000,35129000,24025000,0.030537,None,772000,None,0,76212,0,None,0.004789,None,-0.201392,-1.510845
2022,FY,0.052892,-3.126063,-0.57193,-1.385922,6.750031,12.204015,5.191019,12.204015,0.406077,823981172.56,713514172.56,-15.137252,894.659254,-82.73734,-34.143338,3.877412,3.877412,774.7168,-14.051917,-71.645162,-29.565913,-0.066062,-0.029288,0.026357,0.16023,2.175532,14.051074,None,0.182956,None,0,42.602606,4.715527,0.482571,1.423235,-15.389794,-4.011888,17.290988,29.298236,-0.224223,-0.415723,4.42165,112435000,90391000,80503000,0.033274,4000,500000,None,1.585233,113.636364,0,230.25,3.212,None,-0.25615,-0.813992
2021,FY,0.09524,-2.29198,-1.885138,-2.154661,8.370251,14.923384,8.131968,14.923384,0.103218,862134525,726376525,-22.90596,551.236909,-27.849421,-24.365784,3.517969,3.517969,464.435118,-22.953911,-23.464048,-20.528969,-0.043657,-0.041041,0,0.083513,4.29003,16.111527,None,0.822493,None,0,16.433504,1.721867,0.41708,0.142973,-2.829923,-1.232526,3.725064,27.741525,-0.144574,-0.241469,7.013183,133329000,133540000,119821000,0.006917,32500,572500,None,14.235934,83.100953,0,25.639344,4.392248,None,-0.153583,-0.269523

In [33]:
df_key_metr = df_key_metr.loc[filt_finish_date:filt_start_date].copy(deep=True)
index_years = df_key_metr.index.to_list()

In [34]:
def get_price_from_df(df, list_dates):
    new_list = []
    for i in range(len(list_dates)):
        x = int(list_dates[i])
        # x += 1
        x = str(x)
        r = df.loc[f'{x}-01-01']
        r = float(r)
        new_list.append(r)
        
    return new_list
        
stock_year_prices = get_price_from_df(df, index_years)
stock_year_market_prices = get_price_from_df(df_market, index_years)

In [35]:
df_key_metr[ticker] = list(stock_year_prices)
df_key_metr['SNP'] = list(stock_year_market_prices)
df_key_metr.drop('period', axis=1, inplace=True)

add_percent_columns

In [36]:
def change_percent_all_columns(df):
    x = df.columns.to_list()
    for i in range(len(x)):
        v = df[x[i]].to_list()
        l = []
        for y in range(len(v)):
            try:
                # if y != len(v):
                #     vv = (v[y] / (v[y+1] / 100)) - 100
                #     l.append(vv)
                #     # print(vv)
                if y != len(v):
                    if v[y] < 0 and v[y+1] > 0:
                        l.append('Minus')
                    elif v[y] > 0 and v[y+1] < 0:
                        l.append('Plus')
                    else:
                        vv = (v[y] / (v[y+1] / 100)) - 100
                        l.append(vv)  
                else:
                    vv = 0
                    l.append(vv)
                    # print(vv)
            except:
                l.append(0)
        df[f'change % {x[i]}'] = l
    return df

df_with_changes_key = change_percent_all_columns(df_key_metr)

Vizualization key_metrics

In [37]:
df_with_changes_key = df_with_changes_key.reindex(index=df_with_changes_key.index[::-1])

In [38]:
df_test = df_with_changes_key[[ticker, f'change % {ticker}']]
df_test

                 ATEX  change % ATEX
Date_index
2016        24.070000       0.000000
2017        21.299999     -11.508103
2018        34.400002      61.502360
2019        40.340000      17.267437
2020        46.459999      15.171043
2021        36.279999     -21.911323
2022        51.259998      41.289967

In [ ]:
''' necessary columns '''

km0 = f'{ticker}'
km1 = f'change % {ticker}'
km2 = 'SNP'
km3 = 'change % SNP'
km4 = 'change % debtToAssets'

In [ ]:
# plot size
figure(figsize=(20,4), dpi=150)
plt.axhline(y=0, linestyle='-')


# Set the title and axis labels
plt.title('Percent')
plt.xlabel('Date')
plt.ylabel('Percent')


# Plot 
plt.plot(df_with_changes_key[km1],lw=1, label=km1)
plt.plot(df_with_changes_key[km3],'g',lw=1, label=km3)
plt.plot(df_with_changes_key[km4],'r',lw=1, label=km4)

# Add a legend to the axis
plt.legend()

plt.show()