In [2]:
import fundamentalanalysis as fa
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
import datetime
import statistics as st

%matplotlib inline

In [3]:
# https://pypi.org/project/fundamentalanalysis/

In [4]:
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [5]:
# api_key = '00ef9804fcde0edd93b1b4821ee2f06a'
api_key = 'c81352430e2fe3c941faf0814227562b'

data

In [7]:
''' Колонки '''
ticker = 'AAPL'
# ticker = 'AAPL'


''' время '''
stime='1990-01-01'
ftime='2023-02-01'
period = '1mo'  # '1d' '1wk'

available_companies

In [6]:
available_companies = fa.available_companies(api_key)
available_companies.head(3)

                                                 name   price                 exchange exchangeShortName   type
symbol
YUMC                         Yum China Holdings, Inc.   61.25  New York Stock Exchange              NYSE  stock
ZEAL.CO                            Zealand Pharma A/S  222.40               Copenhagen               CPH  stock
XQB.TO   iShares High Quality Canadian Bond Index ETF   18.82   Toronto Stock Exchange               TSX    etf

profile

In [7]:
profile = fa.profile(ticker, api_key)
profile

                                                                   0
symbol                                                          AAPL
price                                                         143.21
beta                                                         1.27241
volAvg                                                      81327457
mktCap                                                 2267902377984
lastDiv                                                         0.91
range                                                  124.17-179.61
changes                                                     1.350006
companyName                                               Apple Inc.
currency                                                         USD
cik                                                       0000320193
isin                                                    US0378331005
cusip                                                      037833100
exchange                                        NASDAQ Global Select
exchangeShortName                                             NASDAQ
industry                                        Consumer Electronics
website                                        https://www.apple.com
description        Apple Inc. designs, manufactures, and markets ...
ceo                                                 Mr. Timothy Cook
sector                                                    Technology
country                                                           US
fullTimeEmployees                                             164000
phone                                                    14089961010
address                                             1 Apple Park Way
city                                                       Cupertino
state                                                     CALIFORNIA
zip                                                            95014
dcfDiff                                                      8.22176
dcf                                                          150.082
image              https://financialmodelingprep.com/image-stock/...
ipoDate                                                   1980-12-12
defaultImage                                                   False
isEtf                                                          False
isActivelyTrading                                               True
isAdr                                                          False
isFund                                                         False

quote

In [8]:
# '''provides actual information about the company which is, among other things, the day high, market cap, open and close price and price-to-equity ratio'''

quote = fa.quote(ticker, api_key)
quote

                                                 0
symbol                                        AAPL
name                                    Apple Inc.
price                                       143.16
changesPercentage                           0.9164
change                                         1.3
dayLow                                      142.67
dayHigh                                     144.25
yearHigh                                    179.61
yearLow                                     124.17
marketCap                            2267110382838
priceAvg50                                139.2684
priceAvg200                               148.5204
exchange                                    NASDAQ
volume                                    15958621
avgVolume                                 81327457
open                                        143.17
previousClose                               141.86
eps                                           6.11
pe                                           23.43
earningsAnnouncement  2023-02-02T21:00:00.000+0000
sharesOutstanding                      15836199936
timestamp                               1674747960

enterprise

In [9]:
# '''isplays stock price, number of shares, market capitalization and enterprise value over time.'''

enterprise = fa.enterprise(ticker, api_key)
enterprise = enterprise.T
enterprise.head(3)

     symbol  stockPrice numberOfShares  marketCapitalization minusCashAndCashEquivalents  addTotalDebt       enterpriseValue
2022   AAPL  149.449997    16215963000  2423475620080.514648                 23646000000  120069000000  2519898620080.514648
2021   AAPL  148.639999    16701272000  2482477060059.236816                 34940000000  124719000000  2572256060059.236816
2020   AAPL  115.050003    17352119000  1996361344741.568848                 38016000000  112436000000  2070781344741.568848

rating

In [10]:
rating = fa.rating(ticker, api_key)
rating

           rating  ratingScore ratingRecommendation  ratingDetailsDCFScore ratingDetailsDCFRecommendation  ratingDetailsROEScore ratingDetailsROERecommendation  ratingDetailsROAScore ratingDetailsROARecommendation  ratingDetailsDEScore ratingDetailsDERecommendation  ratingDetailsPEScore ratingDetailsPERecommendation  ratingDetailsPBScore ratingDetailsPBRecommendation
date
2023-01-25      S            5           Strong Buy                      5                     Strong Buy                      5                     Strong Buy                      3                        Neutral                     5                    Strong Buy                     5                    Strong Buy                     5                    Strong Buy
2023-01-24      S            5           Strong Buy                      5                     Strong Buy                      5                     Strong Buy                      3                        Neutral                     5                    Strong Buy                     5                    Strong Buy                     5                    Strong Buy
2023-01-23      S            5           Strong Buy                      5                     Strong Buy                      5                     Strong Buy                      3                        Neutral                     5                    Strong Buy                     5                    Strong Buy                     5                    Strong Buy
2023-01-20      S            5           Strong Buy                      5                     Strong Buy                      5                     Strong Buy                      3                        Neutral                     5                    Strong Buy                     5                    Strong Buy                     5                    Strong Buy
2023-01-19      S            5           Strong Buy                      5                     Strong Buy                      5                     Strong Buy                      3                        Neutral                     5                    Strong Buy                     5                    Strong Buy                     5                    Strong Buy
...           ...          ...                  ...                    ...                            ...                    ...                            ...                    ...                            ...                   ...                           ...                   ...                           ...                   ...                           ...
2001-07-09     B+            3              Neutral                      5                     Strong Buy                      3                        Neutral                      3                        Neutral                     4                           Buy                     1                   Strong Sell                     3                       Neutral
2001-07-06     B+            3              Neutral                      5                     Strong Buy                      3                        Neutral                      3                        Neutral                     4                           Buy                     1                   Strong Sell                     3                       Neutral
2001-07-05     B+            3              Neutral                      5                     Strong Buy                      3                        Neutral                      3                        Neutral                     4                           Buy                     1                   Strong Sell                     3                       Neutral
2001-07-03     B+            3              Neutral                      5                     Strong Buy                      3                        Neutral                      3                        Neutral                     4                           Buy                     1                   Strong Sell                     3                       Neutral
2001-07-02     B+            3              Neutral                      5                     Strong Buy                      3                        Neutral                      3                        Neutral                     4                           Buy                     1                   Strong Sell                     3                       Neutral

[5407 rows x 15 columns]

discounted_cash_flow

In [11]:
discounted_cash_flow = fa.discounted_cash_flow(ticker, api_key)
discounted_cash_flow = discounted_cash_flow.T
discounted_cash_flow.head(3)

            date Stock Price         DCF
2023  2023-01-26      143.27  144.718381
2021  2021-09-25  148.639999  150.732056
2020  2020-09-26  115.050003  117.240859

earnings_calendar

In [13]:
# '''premium'''
# earnings_calendar = fa.earnings_calendar(api_key)
# earnings_calendar

income_statement

In [14]:
income_statement = fa.income_statement(ticker, api_key)
income_statement = income_statement.T
income_statement.head(3)

     reportedCurrency         cik fillingDate         acceptedDate calendarYear period       revenue costOfRevenue   grossProfit grossProfitRatio researchAndDevelopmentExpenses generalAndAdministrativeExpenses sellingAndMarketingExpenses sellingGeneralAndAdministrativeExpenses otherExpenses operatingExpenses costAndExpenses interestIncome interestExpense depreciationAndAmortization        ebitda ebitdaratio operatingIncome operatingIncomeRatio totalOtherIncomeExpensesNet incomeBeforeTax incomeBeforeTaxRatio incomeTaxExpense    netIncome netIncomeRatio   eps epsdiluted weightedAverageShsOut weightedAverageShsOutDil                                               link                                          finalLink
2022              USD  0000320193  2022-10-27  2022-10-27 18:01:14         2022     FY  394328000000  223546000000  170782000000         0.433096                    26251000000                                0                           0                             25094000000             0       51345000000    274891000000     2825000000      2931000000                 11104000000  133138000000    0.337633    119437000000             0.302887                  -334000000    119103000000              0.30204      19300000000  99803000000       0.253096  6.15       6.11           16215963000              16325819000  https://www.sec.gov/Archives/edgar/data/320193...  https://www.sec.gov/Archives/edgar/data/320193...
2021              USD  0000320193  2021-10-29  2021-10-28 18:04:28         2021     FY  365817000000  212981000000  152836000000         0.417794                    21914000000                                0                           0                             21973000000             0       43887000000    256868000000     2843000000      2645000000                 11284000000  123136000000    0.336605    108949000000             0.297824                   258000000    109207000000             0.298529      14527000000  94680000000       0.258818  5.67       5.61           16701272000              16864919000  https://www.sec.gov/Archives/edgar/data/320193...  https://www.sec.gov/Archives/edgar/data/320193...
2020              USD  0000320193  2020-10-30  2020-10-29 18:06:25         2020     FY  274515000000  169559000000  104956000000         0.382332                    18752000000                                0                           0                             19916000000             0       38668000000    208227000000     3763000000      2873000000                 11056000000   81020000000    0.295139     66288000000             0.241473                   803000000     67091000000             0.244398       9680000000  57411000000       0.209136  3.31       3.28           17352119000              17528214000  https://www.sec.gov/Archives/edgar/data/320193...  https://www.sec.gov/Archives/edgar/data/320193...

balance_sheet_statement

In [15]:
balance_sheet_statement = fa.balance_sheet_statement(ticker, api_key)
balance_sheet_statement = balance_sheet_statement.T
balance_sheet_statement.head(3)

,reportedCurrency,cik,fillingDate,acceptedDate,calendarYear,period,cashAndCashEquivalents,shortTermInvestments,cashAndShortTermInvestments,netReceivables,inventory,otherCurrentAssets,totalCurrentAssets,propertyPlantEquipmentNet,goodwill,intangibleAssets,goodwillAndIntangibleAssets,longTermInvestments,taxAssets,otherNonCurrentAssets,totalNonCurrentAssets,otherAssets,totalAssets,accountPayables,shortTermDebt,taxPayables,deferredRevenue,otherCurrentLiabilities,totalCurrentLiabilities,longTermDebt,deferredRevenueNonCurrent,deferredTaxLiabilitiesNonCurrent,otherNonCurrentLiabilities,totalNonCurrentLiabilities,otherLiabilities,capitalLeaseObligations,totalLiabilities,preferredStock,commonStock,retainedEarnings,accumulatedOtherComprehensiveIncomeLoss,othertotalStockholdersEquity,totalStockholdersEquity,totalEquity,totalLiabilitiesAndStockholdersEquity,minorityInterest,totalLiabilitiesAndTotalEquity,totalInvestments,totalDebt,netDebt,link,finalLink
2022,USD,0000320193,2022-10-28,2022-10-27 18:01:14,2022,FY,23646000000,24658000000,48304000000,60932000000,4946000000,21223000000,135405000000,42117000000,0,0,0,120805000000,0,54428000000,217350000000,0,352755000000,64115000000,21110000000,0,7912000000,60845000000,153982000000,98959000000,0,0,49142000000,148101000000,0,0,302083000000,0,64849000000,-3068000000,-11109000000,0,50672000000,50672000000,352755000000,0,352755000000,145463000000,120069000000,96423000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
2021,USD,0000320193,2021-10-29,2021-10-28 18:04:28,2021,FY,34940000000,27699000000,62639000000,51506000000,6580000000,14111000000,134836000000,39440000000,0,0,0,127877000000,0,48849000000,216166000000,0,351002000000,54763000000,15613000000,0,7612000000,47493000000,125481000000,109106000000,0,0,53325000000,162431000000,0,0,287912000000,0,57365000000,5562000000,163000000,0,63090000000,63090000000,351002000000,0,351002000000,155576000000,124719000000,89779000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
2020,USD,0000320193,2020-10-30,2020-10-29 18:06:25,2020,FY,38016000000,52927000000,90943000000,37445000000,4061000000,11264000000,143713000000,36766000000,0,0,0,100887000000,0,42522000000,180175000000,0,323888000000,42296000000,13769000000,0,6643000000,42684000000,105392000000,98667000000,0,0,54490000000,153157000000,0,0,258549000000,0,50779000000,14966000000,-406000000,0,65339000000,65339000000,323888000000,0,323888000000,153814000000,112436000000,74420000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...

cash_flow_statement

In [16]:
cash_flow_statement = fa.cash_flow_statement(ticker, api_key)
cash_flow_statement = cash_flow_statement.T
cash_flow_statement.head(3)

     reportedCurrency         cik fillingDate         acceptedDate calendarYear period    netIncome depreciationAndAmortization deferredIncomeTax stockBasedCompensation changeInWorkingCapital accountsReceivables    inventory accountsPayables otherWorkingCapital otherNonCashItems netCashProvidedByOperatingActivities investmentsInPropertyPlantAndEquipment acquisitionsNet purchasesOfInvestments salesMaturitiesOfInvestments otherInvestingActivites netCashUsedForInvestingActivites debtRepayment commonStockIssued commonStockRepurchased dividendsPaid otherFinancingActivites netCashUsedProvidedByFinancingActivities effectOfForexChangesOnCash netChangeInCash cashAtEndOfPeriod cashAtBeginningOfPeriod operatingCashFlow capitalExpenditure  freeCashFlow                                               link                                          finalLink
2022              USD  0000320193  2022-10-28  2022-10-27 18:01:14         2022     FY  99803000000                 11104000000         895000000             9038000000             1200000000         -1823000000   1484000000       9448000000           478000000         111000000                         122151000000                           -10708000000      -306000000           -76923000000                  67363000000             -1780000000                     -22354000000   -9543000000                 0           -89402000000  -14841000000              3037000000                            -110749000000                          0    -10952000000       24977000000             35929000000      122151000000       -10708000000  111443000000  https://www.sec.gov/Archives/edgar/data/320193...  https://www.sec.gov/Archives/edgar/data/320193...
2021              USD  0000320193  2021-10-29  2021-10-28 18:04:28         2021     FY  94680000000                 11284000000       -4774000000             7906000000            -4911000000        -10125000000  -2642000000      12326000000          1676000000        -147000000                         104038000000                           -11085000000       -33000000          -109689000000                 106870000000              -608000000                     -14545000000   -8750000000        1105000000           -85971000000  -14467000000             14730000000                             -93353000000                          0     -3860000000       35929000000             39789000000      104038000000       -11085000000   92953000000  https://www.sec.gov/Archives/edgar/data/320193...  https://www.sec.gov/Archives/edgar/data/320193...
2020              USD  0000320193  2020-10-30  2020-10-29 18:06:25         2020     FY  57411000000                 11056000000        -215000000             6829000000             5690000000          6917000000   -127000000      -4062000000          2081000000         -97000000                          80674000000                            -7309000000     -1524000000          -115148000000                 120483000000              -791000000                      -4289000000  -12629000000         880000000           -72358000000  -14081000000             11368000000                             -86820000000                          0    -10435000000       39789000000             50224000000       80674000000        -7309000000   73365000000  https://www.sec.gov/Archives/edgar/data/320193...  https://www.sec.gov/Archives/edgar/data/320193...

key metrics

In [17]:
key_metrics = fa.key_metrics(ticker, api_key, period='annual')
df_key_metr = key_metrics.T
df_key_metr.head(3)

,period,revenuePerShare,netIncomePerShare,operatingCashFlowPerShare,freeCashFlowPerShare,cashPerShare,bookValuePerShare,tangibleBookValuePerShare,shareholdersEquityPerShare,interestDebtPerShare,marketCap,enterpriseValue,peRatio,priceToSalesRatio,pocfratio,pfcfRatio,pbRatio,ptbRatio,evToSales,enterpriseValueOverEBITDA,evToOperatingCashFlow,evToFreeCashFlow,earningsYield,freeCashFlowYield,debtToEquity,debtToAssets,netDebtToEBITDA,currentRatio,interestCoverage,incomeQuality,dividendYield,payoutRatio,salesGeneralAndAdministrativeToRevenue,researchAndDdevelopementToRevenue,intangiblesToTotalAssets,capexToOperatingCashFlow,capexToRevenue,capexToDepreciation,stockBasedCompensationToRevenue,grahamNumber,roic,returnOnTangibleAssets,grahamNetNet,workingCapital,tangibleAssetValue,netCurrentAssetValue,investedCapital,averageReceivables,averagePayables,averageInventory,daysSalesOutstanding,daysPayablesOutstanding,daysOfInventoryOnHand,receivablesTurnover,payablesTurnover,inventoryTurnover,roe,capexPerShare
2022,FY,24.317273,6.154614,7.532763,6.872426,2.978793,3.124822,3.124822,3.124822,7.585118,2423475620080.514648,2519898620080.514648,24.282593,6.145837,19.839998,21.746324,47.826721,47.826721,6.390362,18.926968,20.629374,22.611547,0.041182,0.045985,1.952933,0.856354,0.724234,0.879356,40.749574,1.223921,0.006124,0.148703,0,0.066571,0,-0.087662,-0.027155,-0.964337,0.02292,20.801964,0.600871,0.282924,-12.679296,-18577000000,None,-166678000000,2.369533,56219000000,59439000000,5763000000,56.400205,104.685277,8.075698,6.471608,3.486641,45.197331,1.969589,-0.660337
2021,FY,21.903541,5.669029,6.229346,5.565624,3.750553,3.777557,3.777557,3.777557,7.626006,2482477060059.236816,2572256060059.236816,26.219656,6.786117,23.861253,26.706799,39.348186,39.348186,7.031538,20.889554,24.724198,27.672652,0.038139,0.037444,1.729371,0.820257,0.729104,1.074553,41.190548,1.098838,0.005828,0.152799,0,0.059904,0,-0.106548,-0.030302,-0.982364,0.021612,21.950838,0.483099,0.269742,-10.978415,9355000000,None,-153076000000,1.976843,51506000000,54763000000,6580000000,51.390969,93.851071,11.276593,7.102415,3.88914,32.367933,1.500713,-0.663722
2020,FY,15.820258,3.308587,4.64923,4.228014,5.241031,3.765477,3.765477,3.765477,6.64524,1996361344741.568848,2070781344741.568848,34.773151,7.272322,24.746031,27.211359,30.553901,30.553901,7.543418,25.558891,25.66851,28.225739,0.028758,0.036749,1.510078,0.798267,0.918539,1.363604,23.072746,1.405201,0.007053,0.245267,0,0.06831,0,-0.090599,-0.026625,-0.661089,0.024877,16.742586,0.303383,0.177256,-7.923629,38321000000,None,-114836000000,1.72081,44475500000,48529500000,5320500000,49.787534,91.04819,8.741883,7.331152,4.008866,41.753016,0.878664,-0.421217

financial_ratios

In [18]:
financial_ratios = fa.financial_ratios(ticker, api_key, period='annual')
financial_ratios = financial_ratios.T
financial_ratios.head(3)

,period,currentRatio,quickRatio,cashRatio,daysOfSalesOutstanding,daysOfInventoryOutstanding,operatingCycle,daysOfPayablesOutstanding,cashConversionCycle,grossProfitMargin,operatingProfitMargin,pretaxProfitMargin,netProfitMargin,effectiveTaxRate,returnOnAssets,returnOnEquity,returnOnCapitalEmployed,netIncomePerEBT,ebtPerEbit,ebitPerRevenue,debtRatio,debtEquityRatio,longTermDebtToCapitalization,totalDebtToCapitalization,interestCoverage,cashFlowToDebtRatio,companyEquityMultiplier,receivablesTurnover,payablesTurnover,inventoryTurnover,fixedAssetTurnover,assetTurnover,operatingCashFlowPerShare,freeCashFlowPerShare,cashPerShare,payoutRatio,operatingCashFlowSalesRatio,freeCashFlowOperatingCashFlowRatio,cashFlowCoverageRatios,shortTermCoverageRatios,capitalExpenditureCoverageRatio,dividendPaidAndCapexCoverageRatio,dividendPayoutRatio,priceBookValueRatio,priceToBookRatio,priceToSalesRatio,priceEarningsRatio,priceToFreeCashFlowsRatio,priceToOperatingCashFlowsRatio,priceCashFlowRatio,priceEarningsToGrowthRatio,priceSalesRatio,dividendYield,enterpriseValueMultiple,priceFairValue
2022,FY,0.879356,0.709408,0.153563,56.400205,8.075698,64.475903,104.685277,-40.209374,0.433096,0.302887,0.30204,0.253096,0.162045,0.282924,1.969589,0.600871,0.837955,0.997204,0.302887,0.856354,5.961537,0.661354,0.703223,40.749574,1.01734,6.961537,6.471608,3.486641,45.197331,9.36268,1.117852,7.532763,6.872426,2.978793,0.148703,0.30977,0.912338,1.01734,5.786405,-11.407452,29.555045,0.148703,47.826721,47.826721,6.145837,24.282593,21.746324,19.839998,19.839998,2.868381,6.145837,0.006124,18.926968,47.826721
2021,FY,1.074553,0.90966,0.278449,51.390969,11.276593,62.667561,93.851071,-31.18351,0.417794,0.297824,0.298529,0.258818,0.133023,0.269742,1.500713,0.483099,0.866977,1.002368,0.297824,0.820257,4.563512,0.633615,0.664074,41.190548,0.834179,5.563512,7.102415,3.88914,32.367933,9.275279,1.042208,6.229346,5.565624,3.750553,0.152799,0.284399,0.893452,0.834179,6.66355,-9.385476,30.762271,0.152799,39.348186,39.348186,6.786117,26.219656,26.706799,23.861253,23.861253,0.367742,6.786117,0.005828,20.889554,39.348186
2020,FY,1.363604,1.218195,0.36071,49.787534,8.741883,58.529418,91.04819,-32.518772,0.382332,0.241473,0.244398,0.209136,0.144282,0.177256,0.878664,0.303383,0.855718,1.012114,0.241473,0.798267,3.957039,0.601606,0.632462,23.072746,0.71751,4.957039,7.331152,4.008866,41.753016,7.466545,0.847562,4.64923,4.228014,5.241031,0.245267,0.293878,0.909401,0.71751,5.859104,-11.037625,11.912877,0.245267,30.553901,30.553901,7.272322,34.773151,27.211359,24.746031,24.746031,3.277438,7.272322,0.007053,25.558891,30.553901

financial_statement_growth

In [19]:
financial_statement_growth = fa.financial_statement_growth(ticker, api_key, period='annual')
financial_statement_growth = financial_statement_growth.T
financial_statement_growth.head(3)

     period revenueGrowth grossProfitGrowth ebitgrowth operatingIncomeGrowth netIncomeGrowth epsgrowth epsdilutedGrowth weightedAverageSharesGrowth weightedAverageSharesDilutedGrowth dividendsperShareGrowth operatingCashFlowGrowth freeCashFlowGrowth tenYRevenueGrowthPerShare fiveYRevenueGrowthPerShare threeYRevenueGrowthPerShare tenYOperatingCFGrowthPerShare fiveYOperatingCFGrowthPerShare threeYOperatingCFGrowthPerShare tenYNetIncomeGrowthPerShare fiveYNetIncomeGrowthPerShare threeYNetIncomeGrowthPerShare tenYShareholdersEquityGrowthPerShare fiveYShareholdersEquityGrowthPerShare threeYShareholdersEquityGrowthPerShare tenYDividendperShareGrowthPerShare fiveYDividendperShareGrowthPerShare threeYDividendperShareGrowthPerShare receivablesGrowth inventoryGrowth assetGrowth bookValueperShareGrowth debtGrowth rdexpenseGrowth sgaexpensesGrowth
2022     FY      0.077938           0.11742   0.096265              0.096265        0.054109  0.084656         0.089127                   -0.029058                          -0.031966                0.056553                  0.1741           0.198918                  3.066899                   1.213792                    0.726431                      2.877012                       1.471791                        1.005162                    2.860169                     1.656418                      1.057405                             -0.30808                             -0.513515                              -0.362129                           8.628423                            0.495769                             0.197333          0.183008       -0.248328    0.004994               -0.172793  -0.037284         0.19791                 0
2021     FY      0.332594          0.456191    0.64357               0.64357        0.649161  0.712991         0.710366                   -0.037508                          -0.037842                0.067451                 0.28961           0.266994                  4.236507                   1.222795                    0.634674                      3.295628                       1.070955                        0.594584                    4.659674                     1.715367                      0.887566                             0.275993                             -0.355431                              -0.301176                                  0                            0.560145                             0.252174          0.375511        0.620291    0.083714                0.003208   0.109244        0.168622                 0
2020     FY      0.055121          0.066713   0.036884              0.036884           0.039  0.106099         0.103448                   -0.060592                          -0.057403                0.061635                  0.1626            0.24567                  5.176488                   0.557805                    0.440242                      5.366885                       0.316614                        0.525593                    5.012479                     0.426055                      0.428033                             1.006393                             -0.273952                              -0.413776                                  0                            0.615369                             0.326249         -0.182495        -0.01096   -0.043212               -0.231352   0.040621        0.156317                 0

last

In [20]:
# stock_data
# stock_data_detailed
#

In [11]:
stock_data

                   low        open       close    high    volume    adjclose
2023-01-26  141.899994  143.169998  143.960007  144.25  54003800  143.960007

In [10]:
stock_data = fa.stock_data(ticker, api_key)
stock_data

                   low        open       close    high    volume    adjclose
2023-01-26  141.899994  143.169998  143.960007  144.25  54003800  143.960007

stock_data_detailed

In [21]:
stock_data_detailed = fa.stock_data_detailed(ticker, api_key)
stock_data_detailed

                open      high       low     close  adjClose     volume unadjustedVolume   change changePercent       vwap            label changeOverTime
2023-01-26    143.17    144.25     141.9    143.96    143.96   54005544         54003800     0.79         0.552     143.37   January 26, 23        0.00552
2023-01-25    140.89    142.43    138.81    141.86    141.86   65802983         65799349     0.97         0.688  141.03333   January 25, 23        0.00688
2023-01-24   140.305    143.15     140.3    142.53    142.53   66440279         66435142    2.225         1.586  141.99333   January 24, 23        0.01586
2023-01-23    138.12    143.32     137.9    141.11    141.11   81702017         81698400     2.99         2.165  140.77667   January 23, 23        0.02165
2023-01-20    135.28    138.02    134.22    137.87    137.87   79976532         79972200     2.59         1.915  136.70333   January 20, 23        0.01915
...              ...       ...       ...       ...       ...        ...              ...      ...           ...        ...              ...            ...
1980-12-18  0.118862   0.11942  0.118862  0.118862  0.092492   73449600         73449600 -0.02637       -22.185    0.11026  December 18, 80       -0.22185
1980-12-17  0.115513  0.116071  0.115513  0.115513  0.089886   86441600         86441600 -0.02563       -22.188    0.10716  December 17, 80       -0.22188
1980-12-16  0.113281  0.113281  0.112723  0.112723  0.087715  105728000        105728000 -0.02557       -22.572    0.10457  December 16, 80       -0.22572
1980-12-15   0.12221   0.12221  0.121652  0.121652  0.094663  175884800        175884800 -0.02755       -22.543    0.11284  December 15, 80       -0.22543
1980-12-12  0.128348  0.128906  0.128348  0.128348  0.099874  469033600        469033600 -0.02847       -22.182    0.11904  December 12, 80       -0.22182

[10620 rows x 12 columns]

In [31]:
y = stock_data_detailed.loc['2022-01-01':'1990-02-15'].copy(deep=True)
y

                  open        high         low       close    adjClose     volume unadjustedVolume   change changePercent       vwap            label changeOverTime
2021-12-31  178.089996  179.229996  177.259995  177.570007   176.54538   64062300         64062300 -1.54462        -0.867  177.67846  December 31, 21       -0.00867
2021-12-30  179.470001  180.570007  178.089996  178.199997  177.171722   59773000         59773000 -2.29828        -1.281  178.61058  December 30, 21       -0.01281
2021-12-29  179.330002  180.630005  178.139999  179.380005   178.34494   62348900         62348900 -0.98506        -0.549  179.03831  December 29, 21       -0.00549
2021-12-28  180.160004  181.330002  178.529999  179.289993  178.255432   79144300         79144300 -1.90457        -1.057  179.37181  December 28, 21       -0.01057
2021-12-27  177.089996  180.419998  177.070007  180.330002  179.289459   74919600         74919600  2.19946         1.242  178.92649  December 27, 21        0.01242
...                ...         ...         ...         ...         ...        ...              ...      ...           ...        ...              ...            ...
1990-02-22    0.303571    0.308036    0.294643    0.294643     0.23542  195182400        195182400 -0.06815       -22.449    0.27937  February 22, 90       -0.22449
1990-02-21    0.292411    0.305804    0.290179    0.303571    0.242554  175907200        175907200 -0.04986       -17.051    0.27951  February 21, 90       -0.17051
1990-02-20    0.299107    0.301339    0.294643    0.299107    0.238987  123244800        123244800 -0.06012         -20.1    0.27832  February 20, 90         -0.201
1990-02-16    0.305804    0.308036    0.301339    0.301339     0.24077  127209600        127209600 -0.06503       -21.265    0.28338  February 16, 90       -0.21265
1990-02-15    0.301339    0.305804    0.299107    0.305804    0.243553   97966400         97966400 -0.05779       -19.178    0.28282  February 15, 90       -0.19178

[8032 rows x 12 columns]

stock_dividend

In [27]:
stock_dividend = fa.stock_dividend(ticker, api_key)
stock_dividend.head(5)

                      label adjDividend dividend  recordDate paymentDate declarationDate
2022-11-04  November 04, 22        0.23     0.23  2022-11-07  2022-11-10      2022-10-27
2022-08-05    August 05, 22        0.23     0.23  2022-08-08  2022-08-11      2022-07-28
2022-05-06       May 06, 22        0.23     0.23  2022-05-09  2022-05-12      2022-04-28
2022-02-04  February 04, 22        0.22     0.22  2022-02-07  2022-02-10      2022-01-27
2021-11-05  November 05, 21        0.22     0.22  2021-11-08  2021-11-11      2021-10-28

In [28]:
x = pd.concat([stock_data_detailed, stock_dividend], axis=1, sort=False)
.tail(10)

                open      high       low     close  adjClose     volume unadjustedVolume   change changePercent     vwap            label changeOverTime            label adjDividend dividend  recordDate paymentDate declarationDate
1980-12-22  0.132254  0.132813  0.132254  0.132254  0.102913   37363200         37363200 -0.02934       -22.185  0.12266  December 22, 80       -0.22185              NaN         NaN      NaN         NaN         NaN             NaN
1980-12-19  0.126116  0.126674  0.126116  0.126116  0.098137   48630400         48630400 -0.02798       -22.186  0.11698  December 19, 80       -0.22186              NaN         NaN      NaN         NaN         NaN             NaN
1980-12-18  0.118862   0.11942  0.118862  0.118862  0.092492   73449600         73449600 -0.02637       -22.185  0.11026  December 18, 80       -0.22185              NaN         NaN      NaN         NaN         NaN             NaN
1980-12-17  0.115513  0.116071  0.115513  0.115513  0.089886   86441600         86441600 -0.02563       -22.188  0.10716  December 17, 80       -0.22188              NaN         NaN      NaN         NaN         NaN             NaN
1980-12-16  0.113281  0.113281  0.112723  0.112723  0.087715  105728000        105728000 -0.02557       -22.572  0.10457  December 16, 80       -0.22572              NaN         NaN      NaN         NaN         NaN             NaN
1980-12-15   0.12221   0.12221  0.121652  0.121652  0.094663  175884800        175884800 -0.02755       -22.543  0.11284  December 15, 80       -0.22543              NaN         NaN      NaN         NaN         NaN             NaN
1980-12-12  0.128348  0.128906  0.128348  0.128348  0.099874  469033600        469033600 -0.02847       -22.182  0.11904  December 12, 80       -0.22182              NaN         NaN      NaN         NaN         NaN             NaN
1995-05-29       NaN       NaN       NaN       NaN       NaN        NaN              NaN      NaN           NaN      NaN              NaN            NaN       May 29, 95    0.001071     0.12  1995-06-02  1995-06-23      1995-05-02
1994-05-30       NaN       NaN       NaN       NaN       NaN        NaN              NaN      NaN           NaN      NaN              NaN            NaN       May 30, 94    0.001071     0.12  1994-06-03  1994-06-24
1990-02-19       NaN       NaN       NaN       NaN       NaN        NaN              NaN      NaN           NaN      NaN              NaN            NaN  February 19, 90    0.000982     0.11  1990-02-23  1990-03-15      1990-02-02

In [30]:
y = 
у

KeyError: '2022'